name: leprecoin
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  get_it: ^7.7.0
  equatable: ^2.0.5
  shared_preferences: ^2.3.1
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  syncfusion_flutter_charts: ^27.1.58
  loading_animation_widget: ^1.3.0
  percent_indicator: ^4.0.1
  intl: ^0.19.0
  core_logic:
    git:
      url: https://github.com/Vennylost/core_logic.git
      ref: 812aadbb74faf0a9dc8a01c2201c03570922e368

  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  advertising_id: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/images/
     - assets/fonts/
     - assets/json/
     - assets/translations/
     - assets/generated/

  fonts:
      - family: satoshi
        fonts:
          - asset: assets/fonts/satoshi-regular.otf
            weight: 400
          - asset: assets/fonts/satoshi-medium.otf
            weight: 500
      - family: avenir
        fonts:
          - asset: assets/fonts/avenir-bold.ttf
            weight: 700
          - asset: assets/fonts/avenir-normal.ttf
            weight: 500

